RogueShoppers/RogueShopper

- package.json
---
Updated package name to 'rogueshopper' in package.json
> update package name for db creation

- server/db/models/order.js
- server/db/models/pet.js
- server/db/models/product.js
- server/db/models/tag.js
- server/db/models/user.js
> Updates models per group discussion

- script/data.js
- script/seed.js
- server/db/models/index.js
- server/db/models/user.js
> Seed script

- client/components/allproducts.js
- client/components/singleProduct.js
- client/components/singleProduct.spec.js
- client/routes.js
- client/store/index.js
- client/store/products.js
- package-lock.json
- server/api/index.js
- server/api/products.js
- server/db/models/index.js
- server/db/models/tag.js
> Single product (updated redux/react/express route)

- server/db/models/product.js
> fixes default image for allProducts

- script/data.js
- script/seed.js
- server/db/models/index.js
- server/db/models/tag.js
> seeding with tags and start of FK seeding

- server/db/models/index.js
> adds associations

- client/components/LogIn.js
- client/components/SignUp.js
- client/components/auth-form.js
- client/components/index.js
- client/components/navbar.js
- client/routes.js
- client/store/index.js
- client/store/user.js
- public/index.html
- public/style.css
- server/auth/index.js
- server/db/models/user.js
> Updated SignIn/SignUp/SignOut & User Model Hash/Salt Working

- server/db/models/index.js
- server/db/models/order-product.js
- server/db/models/order.js
> Updated associations(order-products)

- client/components/navbar.js
- client/routes.js
> adds allproducts to navbar

- server/db/models/user.js
---
Adds virtual field to Users model (full name for admin UI purposes)
> Users model: virtual full name field added

- server/api/adminUser.js
- server/api/adminUser.spec.js
---
Basic GET/PUT/POST/DELETE  routing for admin users laid out on back end, ready for testing to ensure expected functionality
> Admin User back end routing laid out and ready to test

- client/components/allproducts.js
> Link to Single Product Page added to All Products Component

- server/db/models/user.js
---
Removed allowNull: false from preferred name and added isEmail: true to Users model as validators on respective fields. Tested adding new users, works and new users added to db; throws error for incorrect email format (will need to handle error on front end for user)
> Updated User model validators on preferred name and email

- client/components/singleProduct.js
- package-lock.json
- package.json
- tests/allProd.spec.js
> fixed singleProd image bug

- client/components/allproducts.js
> fixes image sizing for all prods

- script/seed.js
> added more toys to seed file, added images to existing toys

- client/components/EditMyAccount.js
- client/components/Home.js
- client/components/navbar.js
- client/store/user.js
- public/index.html
> Navbar: My Cart to show current item count on cart

- client/components/navbar.js
> Updated syntax issue

- client/routes.js
> Added route for homepage to work when logged in

- package-lock.json
- server/api/users.js
- server/index.js
> debugging routes

- client/components/allUsers.js
- client/components/navbar.js
- client/routes.js
- server/api/users.js
> all users view for admins only working

- client/components/MyCart.js
- client/components/MyCartSingleItem.js
- client/components/navbar.js
- client/components/singleProduct.js
- client/store/orders.js
- server/api/orders.js
- server/api/users.js
> Cart checkout functionality completed (backend route cleaned up)

- script/seed.js
> Added more users (now 112 users)

- client/components/MyCart.js
- client/routes.js
- client/store/orders.js
- server/api/orders.js
> Route to Confirmation Page once checkout clicked added

- client/components/MyCart.js
- client/components/MyCartSingleItem.js
- client/components/singleProduct.js
- public/style.css
> singleProduct styling updated & checkout button disabled when cart empty

- client/components/Home.js
- client/components/MyUserAccount.js
- client/store/orders.js
- public/index.html
- server/api/orders.js
> My Account shows order history summary

- server/api/orders.js
> Error handling on backend route (orders - check if user is logged in or not)

- client/components/confirmation.js
- client/components/confirmation.js.rej
> confirmation component updated

- script/seed.js
> seeded products to have 100 products

- client/components/allproducts.js
- client/components/confirmation.js
- client/components/confirmation.js.rej
- client/components/singleProduct.js
> new commit

- client/components/ErrorFormMessage.js
- client/components/LogIn.js
- client/components/SignUp.js
- client/store/user.js
- public/style.css
> Error handling on SignUp & LogIn component (error message display when invalid input)

- client/components/allproducts.js
- client/components/confirmation.js
- client/components/singleProduct.js
- client/store/user.js
- script/seed.js
> Bug fix- navbar logout (remove user reducer updated)

- client/components/MyUserAccount.js
> adds table for my pet future display (currently commented out)

- client/components/MyCart.js
- client/components/MyCartSingleItem.js
- client/store/orders.js
- public/style.css
- script/seed.js
- server/api/orders.js
…rder quantity, display error
---
> inStock updated FE & BE /display error message if purchased quantity is below stock

- client/components/MyUserAccount.js
- client/components/OrderHistoryDetails.js
- client/routes.js
- client/store/orders.js
- package-lock.json
- package.json
- server/api/orders.js
> Past order details pages updated

- client/components/MyCart.js
- client/components/navbar.js
- client/routes.js
- public/style.css
- script/seed.js
- server/api/orders.js
> Guest checkout functionality added (backend & frontend)

- client/components/AdminDashboard.js
- client/components/allUsers.js
- client/components/draft.js
- client/components/navbar.js
- client/routes.js
- script/seed.js
- server/db/models/index.js
---
Started an admin dashboard (Friday night --> going to check if conflicts with what happened yesterday); also added basic order seed data, not currently working and so is commented out. will debug after I fast forward and get caught up
> debug in process - admin dashboard

- client/components/AdminDashboard.js
- client/store/user.js
- server/api/users.js
- server/index.js
---
* Admin dashboard --> link to dashboard appears in Navbar for logged in admin users.
* Component renders visually sections for Users, Products, and Orders, as well as a search bar at top
* Issue with action not being passed to the store, need extra eyes and brains here! I know it's likely something super face->palm/eye roll
* Once this is sorted, component will need a review of the mapping and change/submit handlers to ensure working properly    
* ComponentDidMount currently commented out
> Product admin

- client/components/OrderHistoryDetails.js
- client/routes.js
> Allowed order details for admin users

- client/components/GuestCheckoutForm.js
- client/components/MyCart.js
- client/components/confirmation.js
- client/components/navbar.js
- client/routes.js
- client/store/orders.js
> Guest checkout- guest info form component added

- .travis.yml
- script/seed.js
> cleaned up small error in seed data, edited some travis details

- script/seed.js
> seed data cleanup

- client/components/Home.js
- client/components/allproducts.js
- script/seed.js
> Updated formatting on AllProducts & Home

- client/components/AdminDashboard.js
- client/components/ProductDashboard.js
- client/components/allUsers.js
- client/store/index.js
- client/store/search.js
- client/store/user.js
- server/api/index.js
- server/api/search.js
- server/api/users.spec.js
- server/db/models/product.js
---
**This is in process** --> Routing for search is laid out, currently working on a series of class methods on Products model (which will likely change substantially). Component, Store, Reducer for search all set up and can be utilized for filtering/anything else.
> Admin dashboard

- client/components/navbar.js
> Updated navbar formatting & added coloring for admin vs. users

- script/seed.js
> order-product seeded

- server/api/orders.js
- server/db/models/order.js
- tests/allProd.spec.js
- tests/ordersRoutes.spec.js
> order routes refactored/class methods added

- client/components/allproducts.js
> Updated paginate, add to cart button WIP

- public/index.html
- public/style.css
> font updated

- client/store/orders.js
- server/api/orders.js
- server/api/orders.js.rej
Route refactor for Order GET routes complete
> Refactor complete for order routing

- client/components/singleProduct.js
- server/api/products.js
> Tags added on singleProuduct page

- client/components/allproducts.js
- server/api/users.js
- server/db/models/user.js
> Add product button now with functionality

- client/components/CoreComponents/FilterProducts.js
> Fixed a bug in FilterProducts

- client/components/CoreComponents/MoreLikeThis.js
- client/components/CoreComponents/TagChip.js
- client/components/CoreComponents/allproducts.js
- client/components/CoreComponents/singleProduct.js
- public/style.css
> Tag functionality

- client/components/CartComponents/MyCartSingleItem.js
- client/components/CoreComponents/FilterProducts.js
- client/components/CoreComponents/MoreLikeThis.js
- client/components/CoreComponents/allproducts.js
- client/components/CoreComponents/confirmation.js
- client/components/UserAccountComponents/OrderHistoryDetails.js
- client/routes.js
- public/style.css
> Minor styling added

- client/components/CoreComponents/singleProduct.js
- public/style.css
> minor css update/clean up
